import { ThemeProvider } from "next-themes";
import { Toaster } from "react-hot-toast";
import Providers from "@/components/Providers";
import "@/app/global.css";
import { Roboto_Slab } from 'next/font/google'
import { cn } from "@/lib/utils";

const font = Roboto_Slab({ 
    subsets : ['latin'], 
    weight : ['400', '500', '600', '700', '800', '900']
})

export const metadata = {
    title: "Hackaton",
    description: "Generated by Abdessamad & Mehdi",
    icons : {
        icon : '/plura-logo.svg'
    }
};
const RootLayout = ({ children }) => {
    return (
        <html lang="en">
            <body className={cn('overflow-x-hidden', font.className)}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <Providers>
                        {children}
                        <Toaster
                            position="bottom-right"
                            gutter={12}
                            containerStyle={{ margin: "8px" }}
                            toastOptions={{
                                success: {
                                    duration: 3000,
                                },
                                error: {
                                    duration: 5000,
                                },
                                style: {
                                    fontSize: "16px",
                                    maxWidth: "500px",
                                    padding: "16px 24px",
                                    backgroundColor: "var(--color-grey-0)",
                                    color: "var(--color-grey-700)",
                                },
                            }}
                        />
                    </Providers>
                </ThemeProvider>
            </body>
        </html>
    );
};

export default RootLayout;
